--- # playbook with loops
- hosts: developer
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: add list of users
      user: name="{{ item }}" state=present
      with_items:
        - umair
        - ali
        - zeshaan