# pod with lables

kind: Pod
apiVersion: v1
metadata:
  name: delhipod
  labels:         #  we use lables in metadata                                          
    env: development
    class: pods
spec:
    containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Hafiz Umair; sleep 5 ; done"]


# pod with node selector

# node selector is use when we defined where pod is created or container is run



kind: Pod
apiVersion: v1
metadata:
  name: nodelabels
  labels:
    env: development
spec:
    containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Hello-Umair; sleep 5 ; done"]
    nodeSelector:                                         
       hardware: t2-medium