# pod with one container

kind: Pod                              
apiVersion: v1                     
metadata:                           
  name: testpod                  
spec:                                    
  containers:                      
    - name: c00                     
      image: ubuntu              
      command: ["/bin/bash", "-c", "while true; do echo I am from Kasur; sleep 5 ; done"]
  restartPolicy: Never         # Defaults to Always


# pod with two cnotainer 

kind: Pod
apiVersion: v1
metadata:
  name: testpod1
spec:
  containers:
    - name: c01
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hafiz Umair; sleep 5 ; done"]
    - name: c02
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello Umair; sleep 5 ; done"]