# pod with Replica Set 

kind: ReplicaSet                                    
apiVersion: apps/v1    # This is not available in v1 version                         
metadata:
  name: myrs
spec:
  replicas: 2  
  selector:                  
    matchExpressions:                             # these must match the labels
     - {key: myname, operator: In, values: [Umair, Umar, Hassan]}
     - {key: env, operator: NotIn, values: [production]}
  template:      
    metadata:
      name: testpod7
      labels:              
        myname: Umair
    spec:
     containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Pakistan; sleep 5 ; done"]