# pod with enivironment variable 

kind: Pod
apiVersion: v1
metadata:
  name: environments
spec:
  containers:
name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-Umair; sleep 5 ; done"]
      env:                        # List of environment variables to be used inside the pod
       - name: Name
         value: Umair


# pod with port

kind: Pod
apiVersion: v1
metadata:
  name: testpod4
spec:
  containers:
    - name: c00
      image: httpd
      ports:
       - containerPort: 80  